const express=require("express");
const http=require("http");
const path=require("path");
const crypto=require("crypto");
const Database=require("better-sqlite3");
const bcrypt=require("bcryptjs");
const {Server}=require("socket.io");
const app=express(),server=http.createServer(app),io=new Server(server);
const db=new Database(process.env.DB_FILE||"dear.db");
app.use(express.json()); app.use(express.static(path.join(__dirname,"public")));
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'member');
CREATE TABLE IF NOT EXISTS leads(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT,location TEXT,requirement TEXT,budget TEXT,property_type TEXT,status TEXT,next_followup TEXT,assigned_to INTEGER,source TEXT,notes TEXT,created_by INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS properties(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,location TEXT,price TEXT,details TEXT,status TEXT,created_by INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS notes(id INTEGER PRIMARY KEY AUTOINCREMENT,lead_id INTEGER,user_id INTEGER,note TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,type TEXT,message TEXT,lead_id INTEGER,read INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
const admin=process.env.ADMIN_USERNAME||"arpan",pass=process.env.ADMIN_PASSWORD||"change-me-now";
if(!db.prepare("SELECT id FROM users WHERE username=?").get(admin))db.prepare("INSERT INTO users(name,username,password_hash,role) VALUES(?,?,?,?)").run("Arpan",admin,bcrypt.hashSync(pass,10),"admin");
const sessions=new Map();
function auth(req,res,next){let t=(req.headers.authorization||"").replace("Bearer ",""),u=sessions.get(t);if(!u)return res.status(401).json({error:"Login required"});req.user=u;next()}
function pub(u){return{id:u.id,name:u.name,username:u.username,role:u.role}}
app.post("/api/login",(q,s)=>{let u=db.prepare("SELECT * FROM users WHERE username=?").get(q.body.username);if(!u||!bcrypt.compareSync(q.body.password||"",u.password_hash))return s.status(401).json({error:"Invalid login"});let t=crypto.randomBytes(32).toString("hex");sessions.set(t,pub(u));s.json({token:t,user:pub(u)})});
app.get("/api/users",auth,(q,s)=>s.json(db.prepare("SELECT id,name,username,role FROM users ORDER BY name").all()));
app.post("/api/users",auth,(q,s)=>{if(q.user.role!=="admin")return s.status(403).json({error:"Admin only"});let{x,username,password}=q.body;try{let i=db.prepare("INSERT INTO users(name,username,password_hash,role) VALUES(?,?,?,?)").run(x,username,bcrypt.hashSync(password,10),"member");s.json({id:i.lastInsertRowid})}catch(e){s.status(400).json({error:"Username already exists"})}});
app.delete("/api/users/:id",auth,(q,s)=>{if(q.user.role!=="admin")return s.status(403).json({error:"Admin only"});db.prepare("DELETE FROM users WHERE id=? AND id<>?").run(q.params.id,q.user.id);s.json({ok:true})});
app.get("/api/leads",auth,(q,s)=>s.json(db.prepare(`SELECT l.*,u.name assigned_name,c.name created_by_name FROM leads l LEFT JOIN users u ON u.id=l.assigned_to LEFT JOIN users c ON c.id=l.created_by ORDER BY l.id DESC`).all()));
app.post("/api/leads",auth,(q,s)=>{let x=q.body;if(!x.name||!x.phone)return s.status(400).json({error:"Name and phone required"});let i=db.prepare(`INSERT INTO leads(name,phone,email,location,requirement,budget,property_type,status,next_followup,assigned_to,source,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(x.name,x.phone,x.email||"",x.location||"",x.requirement||"",x.budget||"",x.property_type||"Flat",x.status||"New Lead",x.next_followup||"",x.assigned_to||null,x.source||"Other",x.notes||"",q.user.id);if(x.assigned_to&&+x.assigned_to!==q.user.id){let msg=`New client "${x.name}" assigned to you by ${q.user.name}`;let n=db.prepare("INSERT INTO notifications(user_id,type,message,lead_id) VALUES(?,?,?,?)").run(x.assigned_to,"lead_assigned",msg,i.lastInsertRowid);io.to("user_"+x.assigned_to).emit("notification",{id:n.lastInsertRowid,message:msg,lead_id:i.lastInsertRowid})}io.emit("data_changed");s.json({id:i.lastInsertRowid})});
app.put("/api/leads/:id",auth,(q,s)=>{let old=db.prepare("SELECT * FROM leads WHERE id=?").get(q.params.id),x=q.body;if(!old)return s.status(404).json({error:"Not found"});db.prepare(`UPDATE leads SET name=?,phone=?,email=?,location=?,requirement=?,budget=?,property_type=?,status=?,next_followup=?,assigned_to=?,source=?,notes=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(x.name,x.phone,x.email||"",x.location||"",x.requirement||"",x.budget||"",x.property_type||"Flat",x.status||"New Lead",x.next_followup||"",x.assigned_to||null,x.source||"Other",x.notes||"",q.params.id);if(x.assigned_to&&+x.assigned_to!==+old.assigned_to&&+x.assigned_to!==q.user.id){let msg=`Client "${x.name}" has been assigned to you by ${q.user.name}`;let n=db.prepare("INSERT INTO notifications(user_id,type,message,lead_id) VALUES(?,?,?,?)").run(x.assigned_to,"lead_assigned",msg,q.params.id);io.to("user_"+x.assigned_to).emit("notification",{id:n.lastInsertRowid,message:msg,lead_id:+q.params.id})}io.emit("data_changed");s.json({ok:true})});
app.delete("/api/leads/:id",auth,(q,s)=>{db.prepare("DELETE FROM notes WHERE lead_id=?").run(q.params.id);db.prepare("DELETE FROM leads WHERE id=?").run(q.params.id);io.emit("data_changed");s.json({ok:true})});
app.get("/api/leads/:id/notes",auth,(q,s)=>s.json(db.prepare("SELECT n.*,u.name user_name FROM notes n LEFT JOIN users u ON u.id=n.user_id WHERE lead_id=? ORDER BY n.id DESC").all(q.params.id)));
app.post("/api/leads/:id/notes",auth,(q,s)=>{if(!q.body.note?.trim())return s.status(400).json({error:"Note required"});db.prepare("INSERT INTO notes(lead_id,user_id,note) VALUES(?,?,?)").run(q.params.id,q.user.id,q.body.note.trim());io.emit("data_changed");s.json({ok:true})});
app.get("/api/properties",auth,(q,s)=>s.json(db.prepare(`SELECT p.*,u.name created_by_name FROM properties p LEFT JOIN users u ON u.id=p.created_by ORDER BY p.id DESC`).all()));
app.post("/api/properties",auth,(q,s)=>{let x=q.body,i=db.prepare("INSERT INTO properties(title,location,price,details,status,created_by) VALUES(?,?,?,?,?,?)").run(x.title,x.location||"",x.price||"",x.details||"",x.status||"Available",q.user.id);io.emit("data_changed");s.json({id:i.lastInsertRowid})});
app.put("/api/properties/:id",auth,(q,s)=>{let x=q.body;db.prepare("UPDATE properties SET title=?,location=?,price=?,details=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(x.title,x.location||"",x.price||"",x.details||"",x.status||"Available",q.params.id);io.emit("data_changed");s.json({ok:true})});
app.delete("/api/properties/:id",auth,(q,s)=>{db.prepare("DELETE FROM properties WHERE id=?").run(q.params.id);io.emit("data_changed");s.json({ok:true})});
app.get("/api/notifications",auth,(q,s)=>s.json(db.prepare("SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 50").all(q.user.id)));
app.post("/api/notifications/read",auth,(q,s)=>{db.prepare("UPDATE notifications SET read=1 WHERE user_id=?").run(q.user.id);s.json({ok:true})});
io.on("connection",socket=>socket.on("join",id=>socket.join("user_"+id)));
app.get("*",(q,s)=>s.sendFile(path.join(__dirname,"public","index.html")));
server.listen(process.env.PORT||3000,()=>console.log("DeAr Follow-Up running"));
